// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/bet_data.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BetData struct {
	Index     string                                   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	LotteryId uint64                                   `protobuf:"varint,2,opt,name=lotteryId,proto3" json:"lotteryId,omitempty"`
	Name      string                                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Player    []byte                                   `protobuf:"bytes,4,opt,name=player,proto3" json:"player,omitempty"`
	Amount    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *BetData) Reset()         { *m = BetData{} }
func (m *BetData) String() string { return proto.CompactTextString(m) }
func (*BetData) ProtoMessage()    {}
func (*BetData) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb95574d75f93ab, []int{0}
}
func (m *BetData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BetData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BetData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BetData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetData.Merge(m, src)
}
func (m *BetData) XXX_Size() int {
	return m.Size()
}
func (m *BetData) XXX_DiscardUnknown() {
	xxx_messageInfo_BetData.DiscardUnknown(m)
}

var xxx_messageInfo_BetData proto.InternalMessageInfo

func (m *BetData) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *BetData) GetLotteryId() uint64 {
	if m != nil {
		return m.LotteryId
	}
	return 0
}

func (m *BetData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BetData) GetPlayer() []byte {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *BetData) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*BetData)(nil), "tokenism30924.lottery.lottery.BetData")
}

func init() { proto.RegisterFile("lottery/bet_data.proto", fileDescriptor_cbb95574d75f93ab) }

var fileDescriptor_cbb95574d75f93ab = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xee, 0xf2, 0x67, 0xa8, 0x9e, 0x1a, 0x82, 0x95, 0x68, 0x69, 0x7a, 0x6a, 0xa2, 0xb4, 0xfc,
	0x78, 0xc1, 0x9b, 0xe8, 0x45, 0x8e, 0x3d, 0x6a, 0x0c, 0xd9, 0xb6, 0x9b, 0xda, 0x40, 0x77, 0x1a,
	0x76, 0x21, 0x10, 0xe3, 0x13, 0x78, 0x31, 0xbe, 0x80, 0x89, 0x47, 0x9f, 0x84, 0x23, 0x47, 0x4f,
	0x6a, 0xe0, 0x45, 0x0c, 0xbb, 0xc5, 0x9f, 0x5e, 0xe6, 0x9b, 0x99, 0xef, 0xfb, 0x3a, 0x3b, 0xa3,
	0x56, 0x47, 0xc0, 0x39, 0x19, 0xcf, 0x5d, 0x9f, 0xf0, 0x41, 0x88, 0x39, 0x76, 0xd2, 0x31, 0x70,
	0xd0, 0x8e, 0x38, 0x0c, 0x09, 0x8d, 0x59, 0xd2, 0x69, 0x76, 0xdb, 0xa7, 0x4e, 0xc6, 0xda, 0xc6,
	0x5a, 0x25, 0x82, 0x08, 0x04, 0xd3, 0xdd, 0x20, 0x29, 0xaa, 0xed, 0x07, 0xc0, 0x12, 0x60, 0x03,
	0xd9, 0x08, 0x20, 0xa6, 0x59, 0x43, 0x86, 0xa0, 0x11, 0x11, 0xda, 0x80, 0x94, 0x50, 0x9c, 0xc6,
	0xd3, 0xb6, 0x0b, 0x29, 0x8f, 0x81, 0x32, 0x17, 0x53, 0x0a, 0x1c, 0x0b, 0x2c, 0x89, 0xd6, 0x63,
	0x4e, 0xdd, 0xe9, 0x11, 0x7e, 0x89, 0x39, 0xd6, 0x2a, 0x6a, 0x31, 0xa6, 0x21, 0x99, 0xe9, 0xc8,
	0x44, 0x76, 0xd9, 0x93, 0x89, 0x76, 0xa8, 0x96, 0xb3, 0x59, 0xae, 0x42, 0x3d, 0x67, 0x22, 0xbb,
	0xe0, 0xfd, 0x16, 0x34, 0x4d, 0x2d, 0x50, 0x9c, 0x10, 0x3d, 0x2f, 0x24, 0x02, 0x6b, 0x55, 0xb5,
	0x94, 0x8e, 0xf0, 0x9c, 0x8c, 0xf5, 0x82, 0x89, 0xec, 0x3d, 0x2f, 0xcb, 0xb4, 0x17, 0xa4, 0x96,
	0x70, 0x02, 0x13, 0xca, 0xf5, 0xa2, 0x99, 0xb7, 0x77, 0xdb, 0x07, 0x8e, 0x7c, 0x86, 0xe3, 0x63,
	0x46, 0x9c, 0x69, 0xcb, 0x27, 0x1c, 0xb7, 0x9c, 0x0b, 0x88, 0x69, 0x6f, 0xf4, 0x7c, 0xde, 0xed,
	0x1f, 0xdf, 0xdc, 0x5b, 0x21, 0xa1, 0x90, 0x58, 0x67, 0xa6, 0x25, 0xd6, 0x64, 0x9d, 0x98, 0x96,
	0xb4, 0xd8, 0x94, 0x5a, 0xcd, 0xec, 0xb3, 0x1e, 0x6e, 0x5f, 0x73, 0x65, 0x16, 0x0e, 0x85, 0x98,
	0x2d, 0x3e, 0xea, 0xca, 0xdb, 0x67, 0xdd, 0x8e, 0x62, 0x7e, 0x37, 0xf1, 0x9d, 0x00, 0x12, 0x57,
	0xfe, 0x28, 0x0b, 0x0d, 0x16, 0x0e, 0x5d, 0x3e, 0x4f, 0x09, 0x93, 0x7c, 0x2f, 0x1b, 0xab, 0xd7,
	0x5f, 0xac, 0x0c, 0xb4, 0x5c, 0x19, 0xe8, 0x6b, 0x65, 0xa0, 0xa7, 0xb5, 0xa1, 0x2c, 0xd7, 0x86,
	0xf2, 0xbe, 0x36, 0x94, 0xeb, 0xe6, 0x1f, 0xaf, 0x7f, 0x07, 0x73, 0xb7, 0x67, 0x9d, 0xfd, 0x20,
	0xe1, 0xec, 0x97, 0xc4, 0x82, 0x3b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xd0, 0x9e, 0xc1,
	0xf8, 0x01, 0x00, 0x00,
}

func (m *BetData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BetData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BetData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBetData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Player) > 0 {
		i -= len(m.Player)
		copy(dAtA[i:], m.Player)
		i = encodeVarintBetData(dAtA, i, uint64(len(m.Player)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintBetData(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LotteryId != 0 {
		i = encodeVarintBetData(dAtA, i, uint64(m.LotteryId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintBetData(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBetData(dAtA []byte, offset int, v uint64) int {
	offset -= sovBetData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BetData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovBetData(uint64(l))
	}
	if m.LotteryId != 0 {
		n += 1 + sovBetData(uint64(m.LotteryId))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovBetData(uint64(l))
	}
	l = len(m.Player)
	if l > 0 {
		n += 1 + l + sovBetData(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovBetData(uint64(l))
		}
	}
	return n
}

func sovBetData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBetData(x uint64) (n int) {
	return sovBetData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BetData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBetData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BetData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BetData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBetData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBetData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBetData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LotteryId", wireType)
			}
			m.LotteryId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBetData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LotteryId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBetData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBetData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBetData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBetData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBetData
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBetData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Player = append(m.Player[:0], dAtA[iNdEx:postIndex]...)
			if m.Player == nil {
				m.Player = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBetData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBetData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBetData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBetData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBetData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBetData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBetData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBetData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBetData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBetData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBetData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBetData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBetData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBetData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBetData = fmt.Errorf("proto: unexpected end of group")
)
