// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetLotteryRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetLotteryRequest) Reset()         { *m = QueryGetLotteryRequest{} }
func (m *QueryGetLotteryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLotteryRequest) ProtoMessage()    {}
func (*QueryGetLotteryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{2}
}
func (m *QueryGetLotteryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLotteryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLotteryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLotteryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLotteryRequest.Merge(m, src)
}
func (m *QueryGetLotteryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLotteryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLotteryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLotteryRequest proto.InternalMessageInfo

func (m *QueryGetLotteryRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetLotteryResponse struct {
	Lottery Lottery `protobuf:"bytes,1,opt,name=lottery,proto3" json:"lottery"`
}

func (m *QueryGetLotteryResponse) Reset()         { *m = QueryGetLotteryResponse{} }
func (m *QueryGetLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLotteryResponse) ProtoMessage()    {}
func (*QueryGetLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{3}
}
func (m *QueryGetLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLotteryResponse.Merge(m, src)
}
func (m *QueryGetLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLotteryResponse proto.InternalMessageInfo

func (m *QueryGetLotteryResponse) GetLottery() Lottery {
	if m != nil {
		return m.Lottery
	}
	return Lottery{}
}

type QueryAllLotteryRequest struct {
}

func (m *QueryAllLotteryRequest) Reset()         { *m = QueryAllLotteryRequest{} }
func (m *QueryAllLotteryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllLotteryRequest) ProtoMessage()    {}
func (*QueryAllLotteryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{4}
}
func (m *QueryAllLotteryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLotteryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLotteryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLotteryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLotteryRequest.Merge(m, src)
}
func (m *QueryAllLotteryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLotteryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLotteryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLotteryRequest proto.InternalMessageInfo

type QueryAllLotteryResponse struct {
	Lottery []Lottery `protobuf:"bytes,1,rep,name=lottery,proto3" json:"lottery"`
}

func (m *QueryAllLotteryResponse) Reset()         { *m = QueryAllLotteryResponse{} }
func (m *QueryAllLotteryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllLotteryResponse) ProtoMessage()    {}
func (*QueryAllLotteryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{5}
}
func (m *QueryAllLotteryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLotteryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLotteryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLotteryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLotteryResponse.Merge(m, src)
}
func (m *QueryAllLotteryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLotteryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLotteryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLotteryResponse proto.InternalMessageInfo

func (m *QueryAllLotteryResponse) GetLottery() []Lottery {
	if m != nil {
		return m.Lottery
	}
	return nil
}

type QueryGetBetDataRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetBetDataRequest) Reset()         { *m = QueryGetBetDataRequest{} }
func (m *QueryGetBetDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBetDataRequest) ProtoMessage()    {}
func (*QueryGetBetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{6}
}
func (m *QueryGetBetDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBetDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBetDataRequest.Merge(m, src)
}
func (m *QueryGetBetDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBetDataRequest proto.InternalMessageInfo

func (m *QueryGetBetDataRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetBetDataResponse struct {
	BetData BetData `protobuf:"bytes,1,opt,name=betData,proto3" json:"betData"`
}

func (m *QueryGetBetDataResponse) Reset()         { *m = QueryGetBetDataResponse{} }
func (m *QueryGetBetDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBetDataResponse) ProtoMessage()    {}
func (*QueryGetBetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{7}
}
func (m *QueryGetBetDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBetDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBetDataResponse.Merge(m, src)
}
func (m *QueryGetBetDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBetDataResponse proto.InternalMessageInfo

func (m *QueryGetBetDataResponse) GetBetData() BetData {
	if m != nil {
		return m.BetData
	}
	return BetData{}
}

type QueryAllBetDataRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBetDataRequest) Reset()         { *m = QueryAllBetDataRequest{} }
func (m *QueryAllBetDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllBetDataRequest) ProtoMessage()    {}
func (*QueryAllBetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{8}
}
func (m *QueryAllBetDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBetDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBetDataRequest.Merge(m, src)
}
func (m *QueryAllBetDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBetDataRequest proto.InternalMessageInfo

func (m *QueryAllBetDataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllBetDataResponse struct {
	BetData []BetData `protobuf:"bytes,1,rep,name=betData,proto3" json:"betData"`
}

func (m *QueryAllBetDataResponse) Reset()         { *m = QueryAllBetDataResponse{} }
func (m *QueryAllBetDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllBetDataResponse) ProtoMessage()    {}
func (*QueryAllBetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_559935ceda7539d5, []int{9}
}
func (m *QueryAllBetDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBetDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBetDataResponse.Merge(m, src)
}
func (m *QueryAllBetDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBetDataResponse proto.InternalMessageInfo

func (m *QueryAllBetDataResponse) GetBetData() []BetData {
	if m != nil {
		return m.BetData
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "tokenism30924.lottery.lottery.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "tokenism30924.lottery.lottery.QueryParamsResponse")
	proto.RegisterType((*QueryGetLotteryRequest)(nil), "tokenism30924.lottery.lottery.QueryGetLotteryRequest")
	proto.RegisterType((*QueryGetLotteryResponse)(nil), "tokenism30924.lottery.lottery.QueryGetLotteryResponse")
	proto.RegisterType((*QueryAllLotteryRequest)(nil), "tokenism30924.lottery.lottery.QueryAllLotteryRequest")
	proto.RegisterType((*QueryAllLotteryResponse)(nil), "tokenism30924.lottery.lottery.QueryAllLotteryResponse")
	proto.RegisterType((*QueryGetBetDataRequest)(nil), "tokenism30924.lottery.lottery.QueryGetBetDataRequest")
	proto.RegisterType((*QueryGetBetDataResponse)(nil), "tokenism30924.lottery.lottery.QueryGetBetDataResponse")
	proto.RegisterType((*QueryAllBetDataRequest)(nil), "tokenism30924.lottery.lottery.QueryAllBetDataRequest")
	proto.RegisterType((*QueryAllBetDataResponse)(nil), "tokenism30924.lottery.lottery.QueryAllBetDataResponse")
}

func init() { proto.RegisterFile("lottery/query.proto", fileDescriptor_559935ceda7539d5) }

var fileDescriptor_559935ceda7539d5 = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0x63, 0x4a, 0x13, 0x61, 0x4e, 0xb8, 0xa1, 0x54, 0x11, 0x2c, 0xc8, 0x52, 0x3f, 0x40,
	0xc2, 0x4e, 0x52, 0x28, 0xe2, 0xd8, 0x80, 0x8a, 0x84, 0x38, 0x94, 0x1c, 0x7b, 0x01, 0x6f, 0x6b,
	0x2d, 0x2b, 0x36, 0xeb, 0x6d, 0xd6, 0x41, 0x8d, 0x10, 0x17, 0x9e, 0x00, 0x89, 0x3b, 0x2f, 0x00,
	0x07, 0x78, 0x8b, 0x1e, 0x2b, 0x71, 0xe1, 0x84, 0x50, 0xc2, 0x91, 0x87, 0x40, 0xb1, 0xc7, 0xf9,
	0x5a, 0x68, 0x36, 0x39, 0xed, 0x66, 0x3c, 0x33, 0xff, 0x9f, 0x47, 0xff, 0xc9, 0xe2, 0x95, 0x48,
	0x69, 0x2d, 0xdb, 0x5d, 0x7e, 0xdc, 0x91, 0xed, 0x2e, 0x4b, 0xda, 0x4a, 0x2b, 0x72, 0x43, 0xab,
	0xd7, 0x32, 0x0e, 0xd3, 0xd6, 0x76, 0xf5, 0x61, 0xfd, 0x1e, 0x83, 0x14, 0xf7, 0xac, 0x94, 0x03,
	0x15, 0x28, 0x93, 0xc9, 0x07, 0x6f, 0xb6, 0xa8, 0x72, 0x3d, 0x50, 0x2a, 0x88, 0x24, 0x17, 0x49,
	0xc8, 0x45, 0x1c, 0x2b, 0x2d, 0x74, 0xa8, 0xe2, 0x14, 0x4e, 0xef, 0x1c, 0xaa, 0xb4, 0xa5, 0x52,
	0xee, 0x8b, 0x54, 0x5a, 0x2d, 0xfe, 0xa6, 0xe6, 0x4b, 0x2d, 0x6a, 0x3c, 0x11, 0x41, 0x18, 0x9b,
	0x64, 0xc8, 0x2d, 0x3b, 0xa6, 0x44, 0xb4, 0x45, 0xcb, 0x75, 0xb8, 0xea, 0xa2, 0x0e, 0xc7, 0x86,
	0xaf, 0xb8, 0xb0, 0x2f, 0x35, 0x84, 0x56, 0xc7, 0x42, 0x2f, 0x8e, 0x84, 0x16, 0x36, 0x4e, 0xcb,
	0x98, 0x3c, 0x1f, 0x28, 0xef, 0x9b, 0xb6, 0x4d, 0x79, 0xdc, 0x91, 0xa9, 0xa6, 0x07, 0x78, 0x65,
	0x22, 0x9a, 0x26, 0x2a, 0x4e, 0x25, 0x79, 0x84, 0x8b, 0x56, 0x7e, 0x0d, 0xdd, 0x42, 0x5b, 0x97,
	0xeb, 0xeb, 0xec, 0xdc, 0xa1, 0x30, 0x5b, 0xde, 0xb8, 0x78, 0xfa, 0xf3, 0x66, 0xa1, 0x09, 0xa5,
	0x94, 0xe1, 0x55, 0xd3, 0xfb, 0x89, 0xd4, 0xcf, 0x6c, 0x1e, 0xa8, 0x92, 0x32, 0x5e, 0x0e, 0xe3,
	0x23, 0x79, 0x62, 0xba, 0x5f, 0x6a, 0xda, 0x1f, 0x54, 0xe0, 0x6b, 0x99, 0x7c, 0xe0, 0xd9, 0xc3,
	0x25, 0x90, 0x02, 0xa0, 0x8d, 0x19, 0x40, 0xd0, 0x00, 0x88, 0x5c, 0x31, 0x5d, 0x03, 0xa4, 0xdd,
	0x28, 0x9a, 0x44, 0x1a, 0x8a, 0x8f, 0x9f, 0xfc, 0x4b, 0x7c, 0x69, 0x71, 0xf1, 0xb1, 0x79, 0x34,
	0xa4, 0x7e, 0x2c, 0xb4, 0xc8, 0x3d, 0x8f, 0x61, 0xfe, 0x08, 0xc9, 0xb7, 0xa1, 0x9c, 0xf3, 0x80,
	0x06, 0x0e, 0x09, 0x8a, 0xe9, 0xcb, 0xd1, 0x3c, 0xa6, 0x90, 0xf6, 0x30, 0x1e, 0x59, 0x73, 0x28,
	0x62, 0x7d, 0xcc, 0x06, 0x3e, 0x66, 0x76, 0x67, 0xc0, 0xc7, 0x6c, 0x5f, 0x04, 0x12, 0x6a, 0x9b,
	0x63, 0x95, 0xe3, 0x73, 0x3d, 0xf7, 0x12, 0x4b, 0x0b, 0x5f, 0xa2, 0xfe, 0xa7, 0x88, 0x97, 0x8d,
	0x06, 0xf9, 0x84, 0x70, 0xd1, 0x5a, 0x91, 0xd4, 0x66, 0xf4, 0xca, 0xee, 0x42, 0xa5, 0x3e, 0x4f,
	0x89, 0xbd, 0x03, 0xbd, 0xfb, 0xfe, 0xfb, 0xef, 0x8f, 0x17, 0x36, 0xc9, 0x3a, 0x9f, 0xa8, 0xe5,
	0x53, 0xeb, 0x0a, 0xcb, 0x4c, 0xbe, 0x22, 0x5c, 0x02, 0x77, 0x90, 0xfb, 0x79, 0xe4, 0x32, 0xbb,
	0x53, 0xd9, 0x99, 0xb7, 0x0c, 0x48, 0x77, 0x0c, 0x69, 0x95, 0xb0, 0x19, 0xa4, 0xee, 0xf9, 0xd6,
	0x98, 0xf0, 0x1d, 0xf9, 0x8c, 0x30, 0x86, 0x5e, 0xbb, 0x51, 0x94, 0x8f, 0x3a, 0xb3, 0x5e, 0xf9,
	0xa8, 0xb3, 0xbb, 0x47, 0x99, 0xa1, 0xde, 0x22, 0x1b, 0xf9, 0xa8, 0xc9, 0x37, 0x84, 0x4b, 0x60,
	0x93, 0xdc, 0x03, 0x9e, 0x74, 0x7e, 0xee, 0x01, 0x4f, 0xd9, 0x99, 0x3e, 0x30, 0xa8, 0x35, 0xc2,
	0x67, 0xa0, 0xba, 0xff, 0xe5, 0xe1, 0x84, 0xbf, 0x20, 0x8c, 0xa1, 0xd9, 0x3c, 0x13, 0x5e, 0x04,
	0x3b, 0xbb, 0x85, 0x94, 0x1b, 0xec, 0xdb, 0x64, 0x33, 0x27, 0x76, 0xe3, 0xe9, 0x69, 0xcf, 0x43,
	0x67, 0x3d, 0x0f, 0xfd, 0xea, 0x79, 0xe8, 0x43, 0xdf, 0x2b, 0x9c, 0xf5, 0xbd, 0xc2, 0x8f, 0xbe,
	0x57, 0x38, 0xa8, 0x06, 0xa1, 0x7e, 0xd5, 0xf1, 0xd9, 0xa1, 0x6a, 0xfd, 0xa7, 0xd9, 0xc9, 0xf0,
	0x4d, 0x77, 0x13, 0x99, 0xfa, 0x45, 0xf3, 0x6d, 0xda, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf9,
	0x35, 0x46, 0x59, 0x89, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Lottery by index.
	Lottery(ctx context.Context, in *QueryGetLotteryRequest, opts ...grpc.CallOption) (*QueryGetLotteryResponse, error)
	// Queries a list of Lottery items.
	LotteryAll(ctx context.Context, in *QueryAllLotteryRequest, opts ...grpc.CallOption) (*QueryAllLotteryResponse, error)
	// Queries a BetData by index.
	BetData(ctx context.Context, in *QueryGetBetDataRequest, opts ...grpc.CallOption) (*QueryGetBetDataResponse, error)
	// Queries a list of BetData items.
	BetDataAll(ctx context.Context, in *QueryAllBetDataRequest, opts ...grpc.CallOption) (*QueryAllBetDataResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/tokenism30924.lottery.lottery.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Lottery(ctx context.Context, in *QueryGetLotteryRequest, opts ...grpc.CallOption) (*QueryGetLotteryResponse, error) {
	out := new(QueryGetLotteryResponse)
	err := c.cc.Invoke(ctx, "/tokenism30924.lottery.lottery.Query/Lottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LotteryAll(ctx context.Context, in *QueryAllLotteryRequest, opts ...grpc.CallOption) (*QueryAllLotteryResponse, error) {
	out := new(QueryAllLotteryResponse)
	err := c.cc.Invoke(ctx, "/tokenism30924.lottery.lottery.Query/LotteryAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BetData(ctx context.Context, in *QueryGetBetDataRequest, opts ...grpc.CallOption) (*QueryGetBetDataResponse, error) {
	out := new(QueryGetBetDataResponse)
	err := c.cc.Invoke(ctx, "/tokenism30924.lottery.lottery.Query/BetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BetDataAll(ctx context.Context, in *QueryAllBetDataRequest, opts ...grpc.CallOption) (*QueryAllBetDataResponse, error) {
	out := new(QueryAllBetDataResponse)
	err := c.cc.Invoke(ctx, "/tokenism30924.lottery.lottery.Query/BetDataAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Lottery by index.
	Lottery(context.Context, *QueryGetLotteryRequest) (*QueryGetLotteryResponse, error)
	// Queries a list of Lottery items.
	LotteryAll(context.Context, *QueryAllLotteryRequest) (*QueryAllLotteryResponse, error)
	// Queries a BetData by index.
	BetData(context.Context, *QueryGetBetDataRequest) (*QueryGetBetDataResponse, error)
	// Queries a list of BetData items.
	BetDataAll(context.Context, *QueryAllBetDataRequest) (*QueryAllBetDataResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Lottery(ctx context.Context, req *QueryGetLotteryRequest) (*QueryGetLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lottery not implemented")
}
func (*UnimplementedQueryServer) LotteryAll(ctx context.Context, req *QueryAllLotteryRequest) (*QueryAllLotteryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LotteryAll not implemented")
}
func (*UnimplementedQueryServer) BetData(ctx context.Context, req *QueryGetBetDataRequest) (*QueryGetBetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BetData not implemented")
}
func (*UnimplementedQueryServer) BetDataAll(ctx context.Context, req *QueryAllBetDataRequest) (*QueryAllBetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BetDataAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenism30924.lottery.lottery.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Lottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLotteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Lottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenism30924.lottery.lottery.Query/Lottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Lottery(ctx, req.(*QueryGetLotteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LotteryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLotteryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LotteryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenism30924.lottery.lottery.Query/LotteryAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LotteryAll(ctx, req.(*QueryAllLotteryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenism30924.lottery.lottery.Query/BetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BetData(ctx, req.(*QueryGetBetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BetDataAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllBetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BetDataAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenism30924.lottery.lottery.Query/BetDataAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BetDataAll(ctx, req.(*QueryAllBetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tokenism30924.lottery.lottery.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Lottery",
			Handler:    _Query_Lottery_Handler,
		},
		{
			MethodName: "LotteryAll",
			Handler:    _Query_LotteryAll_Handler,
		},
		{
			MethodName: "BetData",
			Handler:    _Query_BetData_Handler,
		},
		{
			MethodName: "BetDataAll",
			Handler:    _Query_BetDataAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLotteryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLotteryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLotteryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Lottery.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllLotteryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLotteryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLotteryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllLotteryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLotteryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLotteryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Lottery) > 0 {
		for iNdEx := len(m.Lottery) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lottery[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBetDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBetDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBetDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBetDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBetDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBetDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BetData.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllBetDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBetDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBetDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllBetDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBetDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBetDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BetData) > 0 {
		for iNdEx := len(m.BetData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BetData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLotteryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Lottery.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllLotteryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllLotteryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Lottery) > 0 {
		for _, e := range m.Lottery {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetBetDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBetDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BetData.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllBetDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllBetDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BetData) > 0 {
		for _, e := range m.BetData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLotteryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLotteryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLotteryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lottery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Lottery.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLotteryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLotteryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLotteryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLotteryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLotteryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLotteryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lottery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lottery = append(m.Lottery, Lottery{})
			if err := m.Lottery[len(m.Lottery)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBetDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBetDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBetDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBetDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBetDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBetDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BetData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBetDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBetDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBetDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBetDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBetDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBetDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BetData = append(m.BetData, BetData{})
			if err := m.BetData[len(m.BetData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
